"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Check, ChevronRight, Heart, Lock, Palette, ShoppingBag, Sparkles } from "lucide-react";
import BrandLogo from "@/src/components/common/BrandLogo";
import { getAccessToken, getSessionUser, saveSessionUser } from "../services/session";

const ageOptions = [["under-18","Dưới 18"],["18-24","18 – 24"],["25-34","25 – 34"],["35-plus","35+"]];
const roomOptions = [["living-room","Phòng khách"],["bedroom","Phòng ngủ"],["study","Góc làm việc"],["kitchen","Nhà bếp"],["bathroom","Phòng tắm"]];
const styleOptions = [["minimal","Minimal"],["japandi","Japandi"],["soft-pastel","Soft Pastel"],["boho","Boho"],["modern","Modern"]];
const budgetOptions = [["under-25m","Dưới 25 triệu"],["25m-75m","25 – 75 triệu"],["75m-150m","75 – 150 triệu"],["over-150m","Trên 150 triệu"]];
const colorOptions = [["sage-green","#9aaa78","Xanh sage"],["peach","#f2a18c","Cam đào"],["beige","#ddc9aa","Beige"],["lilac","#b9a4df","Lilac"],["blue","#9bc8d1","Xanh lam"],["white","#f7f5ee","Trắng"],["black","#292927","Đen"],["other","#d7a968","Khác"]];
const helpOptions = [["shopping","Mua sắm theo gu","Tìm sản phẩm phù hợp với phong cách."],["moodboards","Moodboard & Combo","Cảm hứng được tuyển chọn cho căn phòng."],["3d-planning","Thiết kế 3D","Xem trước không gian trước khi mua."]];

function Choice({ active, children, onClick }: { active:boolean; children:React.ReactNode; onClick:()=>void }) {
  return <button className={`relative rounded-xl border px-4 py-3 text-left text-sm font-bold transition ${active?"border-[#8aae3d] bg-[#f2f7e5] text-[#344536] shadow-sm":"border-[#ddd8ca] bg-white text-[#69685f] hover:border-[#aab987]"}`} onClick={onClick} type="button">{children}{active&&<Check className="absolute right-2 top-2 text-[#78963d]" size={15}/>}</button>;
}

export default function QuickStyleSetup() {
  const router=useRouter();
  const [ageRange,setAge]=useState("18-24"),[rooms,setRooms]=useState<string[]>(["living-room"]),[styles,setStyles]=useState<string[]>(["japandi"]),[budget,setBudget]=useState("25m-75m"),[colors,setColors]=useState<string[]>(["sage-green","peach","beige"]),[helps,setHelps]=useState<string[]>(["shopping","moodboards","3d-planning"]);
  const [error,setError]=useState(""),[saving,setSaving]=useState(false);
  const toggle=(value:string,list:string[],set:(v:string[])=>void,max=99)=>set(list.includes(value)?list.filter(x=>x!==value):list.length<max?[...list,value]:list);
  async function finish(skipped=false){const token=getAccessToken();if(!token){router.replace("/login");return;}if(!skipped&&(!ageRange||!budget||!rooms.length||!styles.length)){setError("Hãy chọn ít nhất độ tuổi, căn phòng, phong cách và ngân sách nhé.");return;}setSaving(true);setError("");try{const base=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:3001/api").replace(/\/$/,"");const payload=skipped?{skipped:true}:{ageRange,rooms,styles,budget,colors,helpOptions:helps};const response=await fetch(`${base}/users/me/onboarding`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message??"Không thể lưu lựa chọn.");localStorage.setItem("decoho_preferences",JSON.stringify(payload));const user=getSessionUser();if(user)saveSessionUser({...user,onboardingCompleted:true});router.replace("/");}catch(e){setError(e instanceof Error?e.message:"Không thể kết nối máy chủ.");setSaving(false);}}
  return <main className="min-h-screen bg-[#fff9ef] px-4 py-6 text-[#292927] sm:px-6 lg:py-10">
    <div className="mx-auto max-w-[1180px] overflow-hidden rounded-[30px] border border-[#ddd8ca] bg-[#fffdf8] shadow-[0_25px_80px_rgba(70,62,45,.12)]">
      <header className="flex items-center justify-between border-b border-[#e7e1d6] px-5 py-4 sm:px-8"><BrandLogo className="h-12 w-44" variant="horizontal"/><span className="rounded-full bg-[#c7b5e8]/50 px-4 py-2 text-xs font-black">Bước 2 · Thiết lập phong cách ⭐</span></header>
      <div className="px-5 py-7 sm:px-8 lg:px-12">
        <div className="mb-9 flex items-center gap-2">{["Chào mừng","Phong cách","Không gian","Gần xong","Hoàn tất"].map((label,i)=><div className="min-w-0 flex-1 text-center" key={label}><div className={`mx-auto grid h-8 w-8 place-items-center rounded-full text-xs font-black ${i<2?"bg-[#8aae3d] text-white":"border border-[#d7d2c8] bg-white text-[#99958d]"}`}>{i===0?<Check size={15}/>:i+1}</div><p className={`mt-1 hidden truncate text-[10px] sm:block ${i===1?"font-bold text-[#617d2c]":"text-[#8b887f]"}`}>{label}</p></div>)}</div>
        <section className="grid items-center gap-7 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-black tracking-[.2em] text-[#78963d]">NÓI CHÚNG MÌNH BIẾT GU CỦA BẠN ✨</p><h1 className="mt-3 text-4xl leading-[.98] sm:text-6xl">TÌM RA<br/><span className="text-[#f06d5f]">PHONG CÁCH CỦA BẠN</span></h1><p className="mt-4 max-w-lg leading-7 text-[#77746b]">Một vài lựa chọn nhanh để DECOHO cá nhân hóa sản phẩm, moodboard và không gian 3D dành riêng cho bạn.</p></div><div className="relative mx-auto w-full max-w-md rotate-1 rounded-3xl border-[8px] border-white bg-white p-2 shadow-xl"><div className="relative aspect-[16/10] overflow-hidden rounded-2xl"><Image alt="Không gian nội thất truyền cảm hứng" className="object-cover" fill priority src="/images/decoho-home-interior-v2.png"/></div><p className="px-2 pt-3 font-accent text-lg">Good vibes start here ✨</p><span className="absolute -right-4 -top-4 rotate-6 rounded-full bg-[#b9df62] px-4 py-3 text-center text-xs font-black">MADE<br/>FOR YOU</span></div></section>
        <form className="mt-10 grid gap-5 lg:grid-cols-2" onSubmit={(e:FormEvent)=>{e.preventDefault();void finish();}}>
          <section className="rounded-2xl border border-[#ddd8ca] bg-white p-5"><h2 className="font-sans text-lg font-black tracking-normal">1. Bạn thuộc độ tuổi nào?</h2><div className="mt-4 grid grid-cols-2 gap-2">{ageOptions.map(([v,l])=><Choice active={ageRange===v} key={v} onClick={()=>setAge(v)}>{l}</Choice>)}</div></section>
          <section className="rounded-2xl border border-[#ddd8ca] bg-white p-5"><h2 className="font-sans text-lg font-black tracking-normal">2. Bạn quan tâm căn phòng nào?</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{roomOptions.map(([v,l])=><Choice active={rooms.includes(v)} key={v} onClick={()=>toggle(v,rooms,setRooms)}>{l}</Choice>)}</div></section>
          <section className="rounded-2xl border border-[#ddd8ca] bg-white p-5"><h2 className="font-sans text-lg font-black tracking-normal">3. Phong cách bạn yêu thích? <small className="font-normal text-[#77746b]">(tối đa 3)</small></h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{styleOptions.map(([v,l],i)=><Choice active={styles.includes(v)} key={v} onClick={()=>toggle(v,styles,setStyles,3)}><span className={`mb-2 block h-10 rounded-lg ${["bg-stone-200","bg-amber-100","bg-rose-100","bg-orange-100","bg-zinc-200"][i]}`}/>{l}</Choice>)}</div></section>
          <section className="rounded-2xl border border-[#ddd8ca] bg-white p-5"><h2 className="font-sans text-lg font-black tracking-normal">4. Khoảng ngân sách của bạn?</h2><div className="mt-4 grid grid-cols-2 gap-2">{budgetOptions.map(([v,l])=><Choice active={budget===v} key={v} onClick={()=>setBudget(v)}>{l}</Choice>)}</div><p className="mt-3 text-xs text-[#77746b]">🐷 Chúng mình sẽ ưu tiên ý tưởng vừa với ngân sách của bạn.</p></section>
          <section className="rounded-2xl border border-[#ddd8ca] bg-white p-5"><h2 className="font-sans text-lg font-black tracking-normal">5. Màu sắc thu hút bạn? <small className="font-normal text-[#77746b]">(tối đa 4)</small></h2><div className="mt-4 flex flex-wrap gap-4">{colorOptions.map(([v,c,l])=><button className="text-center text-[10px] font-bold" key={v} onClick={()=>toggle(v,colors,setColors,4)} type="button"><span className={`relative mx-auto block h-11 w-11 rounded-full border-2 ${colors.includes(v)?"border-[#78963d] ring-2 ring-[#dce9ba]":"border-white shadow"}`} style={{background:c}}>{colors.includes(v)&&<Check className="absolute inset-0 m-auto text-[#344536]" size={16}/>}</span><span className="mt-1 block">{l}</span></button>)}</div></section>
          <section className="rounded-2xl border border-[#ddd8ca] bg-white p-5"><h2 className="font-sans text-lg font-black tracking-normal">6. Bạn muốn DECOHO hỗ trợ gì?</h2><div className="mt-4 space-y-2">{helpOptions.map(([v,l,d],i)=><Choice active={helps.includes(v)} key={v} onClick={()=>toggle(v,helps,setHelps)}><span className="flex gap-3">{i===0?<ShoppingBag size={18}/>:i===1?<Palette size={18}/>:<Sparkles size={18}/>}<span>{l}<small className="block font-normal text-[#77746b]">{d}</small></span></span></Choice>)}</div></section>
          <div className="lg:col-span-2"><div className="rounded-2xl bg-[#f2f7e5] p-4 text-center text-sm text-[#5f694d]"><Heart className="mr-2 inline text-[#f06d5f]" size={17}/>Chúng mình lưu lựa chọn để cá nhân hóa trải nghiệm. <Lock className="ml-2 inline" size={14}/> Dữ liệu của bạn luôn riêng tư.</div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-center text-sm text-red-700">{error}</p>}<div className="mt-5 flex flex-col-reverse justify-center gap-3 sm:flex-row"><button className="rounded-full border border-[#344536] px-7 py-3 font-bold" disabled={saving} onClick={()=>void finish(true)} type="button">Bỏ qua lúc này</button><button className="inline-flex items-center justify-center gap-2 rounded-full bg-[#8aae3d] px-8 py-3 font-bold text-white disabled:opacity-60" disabled={saving} type="submit">{saving?"Đang lưu...":"Tiếp tục"}<ChevronRight size={18}/></button></div></div>
        </form>
      </div>
    </div>
  </main>;
}
